build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge
  - "conda create -n test-environment python=%PYTHON_VERSION% basemap matplotlib numpy pandas pytables requests pytest shapely geopandas"
  - activate test-environment
  - pip install pycodestyle osmnet
  - python setup.py install

test_script:
  - pycodestyle pandana
  - pytest

after_test:
  - python setup.py bdist_wheel

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
