build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% basemap matplotlib numpy pandas pytables requests pytest"
  - activate test-environment
  # osmnet dependencies
  - conda install -c conda-forge shapely geopandas
  - pip install pycodestyle osmnet
  - pip install .

test_script:
  - pycodestyle pandana
  - pytest